export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BYSIZE = "FILTER_PRODUCTS_BYSIZE";
export const ORDER_PRDUCTS_BY_PRICE = "ORDER_PRDUCTS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
